require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-rake

AllCops:
  Exclude:
    - vendor/bundle/**/*
    - bin/**/*
    - node_modules/**/*
    - db/schema.rb

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/FilePath:
  Enabled: false