language: ruby
services:
  - postgresql
script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rubocop
  - bundle exec brakeman
  - bundle exec bundle-audit check --update
  - bundle exec database_consistency
  - bundle exec rspec