language: ruby
rvm:
  - 2.7
services:
  - postgresql
before_script:
  - psql -c "CREATE USER sharethefood_test WITH PASSWORD 'sharethefood_test_database_password' CREATEDB;" -U postgres
script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec
