language: ruby
rvm:
  - 2.7.1
services:
  - postgresql
  - redis-server
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
before_script:
  - psql -c "CREATE USER sharethefood_test WITH PASSWORD 'sharethefood_test_database_password' SUPERUSER;" -U postgres
script:
  - bundle install
  - NODE_ENV=test bundle exec rails assets:precompile
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec
