language: ruby
rvm:
  - 2.7.0
services:
  - postgresql
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
before_script:
  - psql -c "CREATE USER sharethefood_test WITH PASSWORD 'sharethefood_test_database_password' CREATEDB;" -U postgres
  - NODE_ENV=test bundle exec rails webpacker:compile
script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - bundle exec rspec
